services:
  - type: worker
    name: filterforgebot-worker
    runtime: python
    repo: https://github.com/peacejosephine89-jpg/FilterForgebot
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: python -u bot.py
